//! Keep AI tools out of a repository's credits: `Co-authored-by:` trailers
//! naming an assistant (Claude, Copilot, ChatGPT...), "Generated with ..."
//! footers, and commits authored by an assistant's bot account.
//!
//! `strip` cleans one message, `install` adds a `commit-msg` hook so every new
//! commit is cleaned as it is made, `check` lists the commits that still carry
//! credit, and `rewrite` cleans the existing history (after a backup branch).

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};

/// Names, emails and phrases that mark an assistant rather than a person.
const AI_MARKERS: &[&str] = &[
    "claude",
    "anthropic",
    "copilot",
    "openai",
    "chatgpt",
    "gpt-",
    "codex",
    "gemini",
    "bard",
    "cursor",
    "devin",
    "aider",
    "codeium",
    "windsurf",
    "tabnine",
    "codewhisperer",
    "amazon q",
    "sweep-ai",
    "[bot]",
];

fn is_ai(text: &str) -> bool {
    let t = text.to_ascii_lowercase();
    AI_MARKERS.iter().any(|m| t.contains(m))
}

/// Is this message line credit for an assistant?
pub fn is_credit_line(line: &str) -> bool {
    let l = line.trim();
    let lower = l.to_ascii_lowercase();
    // A co-author trailer naming an assistant (people's trailers stay).
    for key in ["co-authored-by:", "co-developed-by:", "assisted-by:", "generated-by:"] {
        if let Some(rest) = lower.strip_prefix(key) {
            return is_ai(rest);
        }
    }
    // A "made with" footer: "🤖 Generated with [Claude Code](...)" and kin.
    let footer = lower.trim_start_matches(|c: char| !c.is_ascii_alphanumeric());
    let made = ["generated with", "generated by", "created with", "created by", "written with", "written by", "made with", "co-written with", "authored with", "authored by"];
    made.iter().any(|m| footer.starts_with(m)) && is_ai(footer)
}

/// The message with every AI credit line removed (and the blank lines they
/// leave at the end trimmed). A message that was all credit stays empty.
pub fn strip(message: &str) -> String {
    let kept: Vec<&str> = message.lines().filter(|l| !is_credit_line(l)).collect();
    let mut out = kept.join("\n");
    let trimmed = out.trim_end().len();
    out.truncate(trimmed);
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

/// Is this author (name and email) an assistant's account?
pub fn is_ai_author(name: &str, email: &str) -> bool {
    is_ai(name) || is_ai(email)
}

// ------------------------------------------------------------------ commands

/// `cortex ai-credit strip <file|->`: clean a message file in place, or stdin
/// to stdout (as `git filter-branch --msg-filter` wants it).
pub fn run_strip(file: &str) -> Result<()> {
    use std::io::{Read, Write};
    if file == "-" {
        let mut text = String::new();
        std::io::stdin().read_to_string(&mut text)?;
        std::io::stdout().write_all(strip(&text).as_bytes())?;
        return Ok(());
    }
    let text = std::fs::read_to_string(file).with_context(|| format!("cannot read {file}"))?;
    let clean = strip(&text);
    if clean != text {
        std::fs::write(file, clean).with_context(|| format!("cannot write {file}"))?;
    }
    Ok(())
}

fn git(repo: &Path, args: &[&str]) -> Result<String> {
    let out = Command::new("git").arg("-C").arg(repo).args(args).output().context("git not found")?;
    if !out.status.success() {
        bail!("git {}: {}", args.join(" "), String::from_utf8_lossy(&out.stderr).trim());
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

fn hooks_dir(repo: &Path) -> Result<PathBuf> {
    let dir = git(repo, &["rev-parse", "--git-path", "hooks"])?;
    let dir = PathBuf::from(dir.trim());
    Ok(if dir.is_absolute() { dir } else { repo.join(dir) })
}

const HOOK_MARK: &str = "# cortex_suite: ai-credit";

/// `cortex ai-credit install`: a `commit-msg` hook that cleans every new
/// commit's message. A hook already there is kept, as commit-msg.local, and
/// still runs after ours.
pub fn run_install(repo: &Path) -> Result<()> {
    let dir = hooks_dir(repo)?;
    std::fs::create_dir_all(&dir)?;
    let hook = dir.join("commit-msg");
    if let Ok(existing) = std::fs::read_to_string(&hook) {
        if !existing.contains(HOOK_MARK) {
            let keep = dir.join("commit-msg.local");
            std::fs::rename(&hook, &keep)?;
            println!("kept the existing commit-msg hook as {}", keep.display());
        }
    }
    let exe = std::env::current_exe()?.canonicalize()?;
    let script = format!(
        "#!/bin/sh\n{HOOK_MARK}\n# Removes AI co-author credit (Claude, Copilot, ...) from commit messages.\n# Installed by `cortex ai-credit install`; remove this file to stop it.\n\"{}\" ai-credit strip \"$1\" || true\nlocal=\"$(dirname \"$0\")/commit-msg.local\"\n[ -x \"$local\" ] && exec \"$local\" \"$@\"\nexit 0\n",
        exe.display()
    );
    std::fs::write(&hook, script)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&hook, std::fs::Permissions::from_mode(0o755))?;
    }
    println!("installed {}: new commits drop AI co-author credit", hook.display());
    Ok(())
}

/// The commits that still credit an assistant: (hash, subject, why).
fn credited(repo: &Path) -> Result<Vec<(String, String, String)>> {
    // Every branch and tag except the backups `rewrite` leaves.
    let log = git(repo, &["log", "--exclude=backup/*", "--branches", "--tags", "--format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%x1f%B%x1e"])?;
    let mut out = Vec::new();
    for rec in log.split('\x1e') {
        let f: Vec<&str> = rec.trim_start_matches('\n').split('\x1f').collect();
        if f.len() < 7 {
            continue;
        }
        let mut why = Vec::new();
        if is_ai_author(f[1], f[2]) {
            why.push(format!("authored by {}", f[1]));
        }
        if is_ai_author(f[3], f[4]) && f[3] != "GitHub" {
            why.push(format!("committed by {}", f[3]));
        }
        let lines: Vec<&str> = f[6].lines().filter(|l| is_credit_line(l)).collect();
        if !lines.is_empty() {
            why.push(lines.iter().map(|l| l.trim()).collect::<Vec<_>>().join("; "));
        }
        if !why.is_empty() {
            out.push((f[0][..f[0].len().min(9)].to_string(), f[5].to_string(), why.join(" | ")));
        }
    }
    Ok(out)
}

/// `cortex ai-credit check`: list the commits that credit an assistant.
/// Exits 1 when there are any.
pub fn run_check(repo: &Path) -> Result<bool> {
    let found = credited(repo)?;
    if found.is_empty() {
        println!("no AI credit in this repository's history");
        return Ok(true);
    }
    for (hash, subject, why) in &found {
        println!("{hash} {subject}\n    {why}");
    }
    println!("{} commits credit an AI tool. `cortex ai-credit rewrite` removes it.", found.len());
    Ok(false)
}

/// `cortex ai-credit rewrite`: clean the whole history -- credit lines out of
/// every message, an assistant's commits re-authored to `author` (default:
/// this repo's git user). Saves a backup branch first; the tree must be clean.
/// Rewritten history has to be force-pushed, which is left to the user.
pub fn run_rewrite(repo: &Path, author: Option<&str>) -> Result<()> {
    if !git(repo, &["status", "--porcelain", "--untracked-files=no"])?.trim().is_empty() {
        bail!("commit or stash your changes first: rewriting needs a clean tree");
    }
    let (name, email) = match author {
        Some(a) => {
            let (n, e) = a.rsplit_once('<').context("--author must look like \"Name <email>\"")?;
            (n.trim().to_string(), e.trim_end_matches('>').trim().to_string())
        }
        None => (git(repo, &["config", "user.name"])?.trim().to_string(), git(repo, &["config", "user.email"])?.trim().to_string()),
    };
    if name.is_empty() || email.is_empty() {
        bail!("no author to give the assistants' commits: pass --author \"Name <email>\"");
    }
    let before = credited(repo)?.len();
    if before == 0 {
        println!("nothing to rewrite: no AI credit in the history");
        return Ok(());
    }
    let stamp = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0);
    let backup = format!("backup/before-ai-credit-{stamp}");
    git(repo, &["branch", &backup])?;
    println!("saved the current history as branch {backup}");

    let exe = std::env::current_exe()?.canonicalize()?;
    let markers = AI_MARKERS.iter().map(|m| m.replace('[', "\\[").replace(']', "\\]")).collect::<Vec<_>>().join("|");
    // Shell side of the author swap: an author or committer matching a marker
    // becomes the person given.
    let env_filter = format!(
        "is_ai() {{ printf '%s' \"$1\" | tr 'A-Z' 'a-z' | grep -Eq '{markers}'; }}\n\
         if is_ai \"$GIT_AUTHOR_NAME $GIT_AUTHOR_EMAIL\"; then GIT_AUTHOR_NAME='{n}'; GIT_AUTHOR_EMAIL='{e}'; export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL; fi\n\
         if is_ai \"$GIT_COMMITTER_NAME $GIT_COMMITTER_EMAIL\"; then GIT_COMMITTER_NAME='{n}'; GIT_COMMITTER_EMAIL='{e}'; export GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL; fi",
        n = name.replace('\'', ""),
        e = email.replace('\'', "")
    );
    let msg_filter = format!("\"{}\" ai-credit strip -", exe.display());
    // Every branch and tag but the backups, which must keep the old history.
    let refs: Vec<String> = git(repo, &["for-each-ref", "--format=%(refname)", "refs/heads", "refs/tags"])?
        .lines()
        .filter(|r| !r.starts_with("refs/heads/backup/"))
        .map(str::to_string)
        .collect();
    let status = Command::new("git")
        .arg("-C")
        .arg(repo)
        .env("FILTER_BRANCH_SQUELCH_WARNING", "1")
        .args(["filter-branch", "-f", "--env-filter", &env_filter, "--msg-filter", &msg_filter, "--"])
        .args(&refs)
        .status()
        .context("git filter-branch failed to start")?;
    if !status.success() {
        bail!("git filter-branch failed; the old history is still on branch {backup}");
    }
    let after = credited(repo)?.len();
    println!("rewrote the history: {before} commits had AI credit, {after} still do ({backup} keeps the old history)");
    println!("to publish it: git push --force-with-lease (everyone else must re-clone or reset)");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_assistant_trailers_and_footers() {
        let msg = "Fix the parser\n\nLonger body.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\nCo-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>\n";
        assert_eq!(strip(msg), "Fix the parser\n\nLonger body.\n");
    }

    #[test]
    fn keeps_people() {
        let msg = "Merge\n\nCo-authored-by: Artistsyn <250262773+Artistsyn@users.noreply.github.com>\n";
        assert_eq!(strip(msg), msg);
        assert!(!is_credit_line("Generated the tables with a script"));
        assert!(!is_credit_line("Explain how Claude-style prompts are parsed"));
    }

    #[test]
    fn knows_bot_authors() {
        assert!(is_ai_author("copilot-swe-agent[bot]", "198982749+Copilot@users.noreply.github.com"));
        assert!(!is_ai_author("Artistsyn", "artistsyn@gmail.com"));
    }
}
