//! Skills without a person approving each one (docs/self-learning-loop-2026-09-30.md, L5).
//!
//! Every skill decision so far was made by hand, and every one is predictable
//! from the draft itself. Replayed over all 15 on 2026-09-30:
//!
//! - the 3 rejected and the 2 still waiting were detector templates, their
//!   "use when" still reading "[Edit: describe when ...]";
//! - the 10 approved were written by an agent or a person: no placeholder, a
//!   concrete "use when", and a body of 2,600-9,500 characters.
//!
//! So noise is rejected automatically and credible drafts are published as
//! TRIALS. SkillsBench found no average benefit from self-generated skills, so
//! a trial has to earn its place by being used: one invoked within 60 days is
//! approved, one nobody invoked is retired (unpublished; its draft is kept).
//! Anything the rules cannot place stays for a person.

use std::path::{Path, PathBuf};

use anyhow::Result;
use rusqlite::params;

use crate::memory::Store;

/// Days a trial has to be used.
pub const TRIAL_DAYS: i64 = 60;
/// A credible draft carries a real body, not a stub.
const MIN_BODY_CHARS: usize = 1_500;

#[derive(Debug, PartialEq, Eq)]
pub enum Class {
    Noise(String),
    Credible,
    Unsure(String),
}

fn section<'a>(text: &'a str, heading: &str) -> Option<&'a str> {
    let start = text.find(&format!("## {heading}"))?;
    let rest = &text[start..];
    let body_start = rest.find('\n').map(|i| i + 1).unwrap_or(rest.len());
    let body = &rest[body_start..];
    Some(body.split("\n## ").next().unwrap_or(body))
}

/// Decide from the draft alone.
pub fn classify(draft: &str) -> Class {
    let detector = draft.contains("Auto-generated by cortex detect-skills");
    let placeholder = draft.contains("[Edit:");
    let when = section(draft, "Use This Skill When").filter(|s| {
        !s.contains("[Edit") && s.lines().any(|l| l.trim_start().starts_with("- ") && l.trim().len() > 4)
    });
    if detector && (placeholder || when.is_none()) {
        return Class::Noise(if placeholder {
            "a detector template still holding its placeholders".into()
        } else {
            "a detector template with no concrete \"use when\"".into()
        });
    }
    if detector {
        return Class::Unsure("a detector draft someone filled in: a person reads it".into());
    }
    if placeholder {
        return Class::Unsure("an authored draft that still holds a placeholder".into());
    }
    if when.is_none() {
        return Class::Unsure("no concrete \"use when\": nothing tells an agent when to invoke it".into());
    }
    if draft.chars().count() < MIN_BODY_CHARS {
        return Class::Unsure(format!("under {MIN_BODY_CHARS} characters: too thin to judge"));
    }
    Class::Credible
}

#[derive(Debug, Default)]
pub struct Triage {
    pub rejected: Vec<(String, String)>,
    pub trials: Vec<(String, Vec<PathBuf>)>,
    pub left: Vec<(String, String)>,
    pub approved: Vec<(String, usize)>,
    pub retired: Vec<String>,
}

impl Triage {
    pub fn summary(&self) -> String {
        let mut o = Vec::new();
        for (n, why) in &self.rejected {
            o.push(format!("rejected {n}: {why}"));
        }
        for (n, paths) in &self.trials {
            o.push(format!("trial {n}: published to {}", paths.iter().map(|p| p.display().to_string()).collect::<Vec<_>>().join(", ")));
        }
        for (n, uses) in &self.approved {
            o.push(format!("approved {n}: invoked {uses} time(s) during its trial"));
        }
        for n in &self.retired {
            o.push(format!("retired {n}: not invoked in {TRIAL_DAYS} days (unpublished; the draft is kept)"));
        }
        for (n, why) in &self.left {
            o.push(format!("left for a person: {n} ({why})"));
        }
        o.join("\n")
    }
}

fn draft_file(repo_root: &Path, name: &str, draft_path: Option<String>) -> Option<PathBuf> {
    [draft_path.map(PathBuf::from), Some(repo_root.join(".cortex/proposals").join(format!("skill_{name}.md")))]
        .into_iter()
        .flatten()
        .map(|p| if p.is_absolute() { p } else { repo_root.join(p) })
        .find(|p| p.exists())
}

fn published_paths(repo_root: &Path, skills_dir: &Path, name: &str) -> Vec<PathBuf> {
    let safe = name.replace(['/', '\\', ' '], "-");
    vec![
        skills_dir.join(&safe),
        repo_root.join(".github/prompts").join(format!("{safe}.prompt.md")),
    ]
}

/// Times a skill was invoked in Claude Code transcripts modified since
/// `since`: the Skill tool, or the user typing `/<name>`.
pub fn count_invocations(dir: &Path, name: &str, since: i64) -> usize {
    let Ok(files) = crate::capture::transcripts(dir) else { return 0 };
    let as_tool = format!("\"skill\":\"{name}\"");
    let as_command = format!("<command-name>/{name}</command-name>");
    let mut n = 0;
    for f in files {
        let modified = std::fs::metadata(&f)
            .and_then(|m| m.modified())
            .ok()
            .and_then(|m| m.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        if modified < since {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&f) else { continue };
        for line in text.lines() {
            let recent = serde_json::from_str::<serde_json::Value>(line)
                .ok()
                .and_then(|v| v.get("timestamp").and_then(|t| t.as_str()).map(str::to_string))
                .and_then(|t| chrono::DateTime::parse_from_rfc3339(&t).ok())
                .is_some_and(|t| t.timestamp() >= since);
            if recent && ((line.contains("\"name\":\"Skill\"") && line.contains(&as_tool)) || line.contains(&as_command)) {
                n += 1;
            }
        }
    }
    n
}

/// Triage the drafts and review the trials, publishing into `skills_dir` (the
/// preference skill-approve uses). `dry_run` reports without acting.
pub fn run(store: &Store, repo_root: &Path, skills_dir: &Path, transcripts: Option<&Path>, dry_run: bool) -> Result<Triage> {
    let mut t = Triage::default();
    let drafted: Vec<(String, Option<String>)> = {
        let mut stmt = store.conn().prepare("SELECT name, draft_path FROM skill_candidates WHERE status = 'drafted' ORDER BY name")?;
        let rows = stmt.query_map([], |r| Ok((r.get(0)?, r.get(1)?)))?;
        rows.filter_map(|r| r.ok()).collect()
    };
    for (name, path) in drafted {
        let Some(file) = draft_file(repo_root, &name, path) else {
            t.left.push((name, "no draft file on disk".into()));
            continue;
        };
        match classify(&std::fs::read_to_string(&file)?) {
            Class::Noise(why) => {
                if !dry_run {
                    crate::skills::set_skill_status(store, &name, "rejected")?;
                    crate::loop_ledger::record(store, &crate::loop_ledger::NewChange {
                        class: "skill",
                        target: &format!("skill:{name}"),
                        before: "drafted",
                        after: "rejected",
                        evidence: &why,
                        ..Default::default()
                    })?;
                }
                t.rejected.push((name, why));
            }
            Class::Credible => {
                let prompts = repo_root.join(".github");
                let paths = if dry_run {
                    Vec::new()
                } else {
                    let written = crate::skills::publish_skill(
                        &name,
                        &file,
                        skills_dir,
                        prompts.is_dir().then(|| repo_root.join(".github/prompts")).as_deref(),
                        false,
                    )?;
                    crate::skills::set_skill_status(store, &name, "trial")?;
                    crate::loop_ledger::record(store, &crate::loop_ledger::NewChange {
                        class: "skill-trial",
                        target: &format!("skill:{name}"),
                        before: "drafted",
                        after: "trial",
                        evidence: &written.iter().map(|p| p.display().to_string()).collect::<Vec<_>>().join(", "),
                        ..Default::default()
                    })?;
                    written
                };
                t.trials.push((name, paths));
            }
            Class::Unsure(why) => t.left.push((name, why)),
        }
    }
    // Trials that have had their time.
    let now = chrono::Utc::now().timestamp();
    let trials: Vec<(String, i64)> = {
        let mut stmt = store.conn().prepare(
            "SELECT s.name, COALESCE((SELECT MAX(c.created_at) FROM loop_changes c
                                      WHERE c.class = 'skill-trial' AND c.target = 'skill:' || s.name), 0)
             FROM skill_candidates s WHERE s.status = 'trial'",
        )?;
        let rows = stmt.query_map([], |r| Ok((r.get(0)?, r.get(1)?)))?;
        rows.filter_map(|r| r.ok()).collect()
    };
    for (name, started) in trials {
        if now - started < TRIAL_DAYS * 86_400 {
            continue;
        }
        let uses = transcripts.map(|d| count_invocations(d, &name, started)).unwrap_or(0);
        if uses > 0 {
            if !dry_run {
                crate::skills::set_skill_status(store, &name, "approved")?;
                crate::loop_ledger::record(store, &crate::loop_ledger::NewChange {
                    class: "skill",
                    target: &format!("skill:{name}"),
                    before: "trial",
                    after: "approved",
                    evidence: &format!("invoked {uses} time(s) during its trial"),
                    ..Default::default()
                })?;
            }
            t.approved.push((name, uses));
        } else {
            if !dry_run {
                for p in published_paths(repo_root, skills_dir, &name) {
                    if p.is_dir() {
                        let _ = std::fs::remove_dir_all(&p);
                    } else if p.exists() {
                        let _ = std::fs::remove_file(&p);
                    }
                }
                crate::skills::set_skill_status(store, &name, "retired")?;
                crate::loop_ledger::record(store, &crate::loop_ledger::NewChange {
                    class: "skill",
                    target: &format!("skill:{name}"),
                    before: "trial",
                    after: "retired",
                    evidence: &format!("not invoked in {TRIAL_DAYS} days"),
                    ..Default::default()
                })?;
            }
            t.retired.push(name);
        }
    }
    Ok(t)
}

pub fn trial_count(store: &Store) -> i64 {
    store
        .conn()
        .query_row("SELECT COUNT(*) FROM skill_candidates WHERE status = 'trial'", [], |r| r.get(0))
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    const DETECTOR: &str = "# workflow-recall\n<!-- Auto-generated by cortex detect-skills -->\n\n## Purpose\n\nAuto-detected.\n\n## Use This Skill When\n\n- [Edit: describe when to invoke this skill based on user requests]\n\n## Procedure\n\n1. Call `recall`\n";

    fn authored(body_chars: usize) -> String {
        format!(
            "# verify-ui-layout-by-rendering\n<!-- Agent-authored via propose_skill | Drafted: 2026-08-05 -->\n\n## Use This Skill When\n\n- a layout looks wrong in a screenshot\n\n## Procedure\n\n{}\n",
            "Render the component headlessly and measure it. ".repeat(body_chars / 48 + 1)
        )
    }

    #[test]
    fn the_history_is_reproduced() {
        // Every rejection so far was a detector template with its placeholders.
        assert!(matches!(classify(DETECTOR), Class::Noise(_)));
        // Every approval was authored, concrete and substantial.
        assert_eq!(classify(&authored(3_000)), Class::Credible);
        // A stub, a leftover placeholder or no "use when" goes to a person.
        assert!(matches!(classify(&authored(200)), Class::Unsure(_)));
        assert!(matches!(classify(&authored(3_000).replace("a layout looks wrong", "[Edit: when]")), Class::Unsure(_)));
        let filled = DETECTOR.replace("- [Edit: describe when to invoke this skill based on user requests]", "- recalling a known trap");
        assert!(matches!(classify(&filled), Class::Unsure(_)), "a filled-in detector draft is a person's call");
    }

    #[test]
    fn noise_is_rejected_credible_drafts_become_trials_and_unused_trials_retire() {
        let s = crate::test_support::TempStore::new("skill_triage").unwrap();
        let root = std::env::temp_dir().join(format!("cortex-skills-{}", std::process::id()));
        let proposals = root.join(".cortex/proposals");
        std::fs::create_dir_all(&proposals).unwrap();
        std::fs::create_dir_all(root.join(".github")).unwrap();
        std::fs::write(proposals.join("skill_workflow-recall.md"), DETECTOR).unwrap();
        std::fs::write(proposals.join("skill_verify-ui.md"), authored(3_000)).unwrap();
        for name in ["workflow-recall", "verify-ui"] {
            s.conn().execute("INSERT INTO skill_candidates (name, status) VALUES (?1, 'drafted')", params![name]).unwrap();
        }
        let skills = root.join(".claude/skills");
        let dry = run(&s, &root, &skills, None, true).unwrap();
        assert_eq!((dry.rejected.len(), dry.trials.len()), (1, 1));
        let status = |n: &str| -> String {
            s.conn().query_row("SELECT status FROM skill_candidates WHERE name = ?1", params![n], |r| r.get(0)).unwrap()
        };
        assert_eq!(status("workflow-recall"), "drafted", "a dry run changes nothing");

        let t = run(&s, &root, &skills, None, false).unwrap();
        assert_eq!(status("workflow-recall"), "rejected");
        assert_eq!(status("verify-ui"), "trial");
        assert!(root.join(".claude/skills/verify-ui/SKILL.md").exists());
        assert!(root.join(".github/prompts/verify-ui.prompt.md").exists());
        assert_eq!(t.trials.len(), 1);

        // Sixty days later, nobody used it: it is unpublished and retired.
        s.conn().execute("UPDATE loop_changes SET created_at = created_at - 61 * 86400 WHERE class = 'skill-trial'", []).unwrap();
        let later = run(&s, &root, &skills, Some(&root), false).unwrap();
        assert_eq!(later.retired, vec!["verify-ui".to_string()]);
        assert_eq!(status("verify-ui"), "retired");
        assert!(!root.join(".claude/skills/verify-ui").exists());
        assert!(proposals.join("skill_verify-ui.md").exists(), "the draft is kept");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn invocations_are_counted_from_transcripts() {
        let dir = std::env::temp_dir().join(format!("cortex-skill-uses-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let now = chrono::Utc::now().to_rfc3339();
        let tool = serde_json::json!({"type": "assistant", "timestamp": now, "message": {"content": [{"type": "tool_use", "name": "Skill", "input": {"skill": "frontier"}}]}});
        let slash = serde_json::json!({"type": "user", "timestamp": now, "message": {"content": "<command-name>/frontier</command-name>"}});
        std::fs::write(dir.join("s.jsonl"), format!("{tool}\n{slash}\n")).unwrap();
        assert_eq!(count_invocations(&dir, "frontier", 0), 2);
        assert_eq!(count_invocations(&dir, "other", 0), 0);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
